/** Extension version in the template and its default for `apiVersion`. */
export const INITIAL_VERSION = '0.1.0';

export const TEMPLATE_NAMES = [
  'exercise',
  'theme',
  'command-panel',
  'events',
  'blank',
] as const;
export type TemplateName = (typeof TEMPLATE_NAMES)[number];
export const DEFAULT_TEMPLATE: TemplateName = 'exercise';

export interface TemplateInput {
  id: string;
  /** Project kind; defaults to `exercise`. */
  template?: TemplateName;
  /** Dependency specifiers for the SDK and tools (see `dependencySpecs`). */
  dependencies: { api: string; sdk: string; tools: string };
}

/** What differs between project kinds; the rest of the project is shared. */
export interface TemplateModule {
  /** README paragraph: what the project does. */
  summary: readonly string[];
  /** Bullets of the "Layout" section (README and AGENTS.md). */
  layout: readonly string[];
  /** Project-specific files: relative path → content. */
  files(id: string): Record<string, string>;
}

export const lines = (parts: readonly string[]): string =>
  `${parts.join('\n')}\n`;

/** The `pnpm` scripts of every generated project. */
export const scripts = (id: string): Record<string, string> => ({
  build: 'dolphy-ext build',
  dev: 'dolphy-ext build --watch',
  types: 'dolphy-ext types',
  typecheck: 'dolphy-ext types && tsc',
  validate: `dolphy-ext validate dist-ext/${id}`,
  lint: 'dolphy-ext lint',
  test: 'vitest run',
});

export const packageJson = ({ id, dependencies }: TemplateInput): string =>
  `${JSON.stringify(
    {
      name: id,
      version: INITIAL_VERSION,
      private: true,
      type: 'module',
      scripts: scripts(id),
      devDependencies: {
        '@dolphy-app/extension-api': dependencies.api,
        '@dolphy-app/extension-sdk': dependencies.sdk,
        '@dolphy-app/extension-tools': dependencies.tools,
        '@types/node': '^22.20.4',
        'happy-dom': '^20.14.5',
        typescript: '^6.0.3',
        vitest: '^5.0.2',
      },
    },
    null,
    2,
  )}\n`;

export const tsconfigJson = (): string =>
  lines([
    '{',
    '  "compilerOptions": {',
    '    "target": "ES2023",',
    '    "lib": ["ES2023", "DOM"],',
    '    "module": "ESNext",',
    '    "moduleResolution": "bundler",',
    '    "types": ["node"],',
    '    "strict": true,',
    '    "resolveJsonModule": true,',
    '    "allowImportingTsExtensions": true,',
    '    "verbatimModuleSyntax": true,',
    '    "isolatedModules": true,',
    '    "skipLibCheck": true,',
    '    "noEmit": true',
    '  },',
    '  "include": ["src", "test", ".dolphy/ids.d.ts"]',
    '}',
  ]);

export const idsBullet: readonly string[] = [
  '- `.dolphy/ids.d.ts` — generated from `extension.json` by',
  '  `dolphy-ext types` (and by every build): the ids the manifest declares,',
  '  as TypeScript types. Not committed. A misspelt id, a declared id without',
  '  a handler or a view, or `ctx.settings.get` of an undeclared setting fails',
  '  `pnpm typecheck`;',
];

export const readme = (id: string, module: TemplateModule): string =>
  lines([
    `# ${id}`,
    '',
    ...module.summary,
    'Generated by `create-dolphy-extension`.',
    '',
    '## Layout',
    '',
    ...module.layout,
    '',
    '## Development loop',
    '',
    '```sh',
    'pnpm install',
    `pnpm dev # dolphy-ext build --watch: rebuilds into dist-ext/${id}`,
    '```',
    '',
    'Start the app with the developer root pointing at the `dist-ext` directory',
    'of this project (an absolute path):',
    '',
    '```sh',
    'DOLPHY_DEV_EXTENSIONS=<path to the project>/dist-ext pnpm dev # from the Dolphy repository',
    '```',
    '',
    'A change to a file in `dist-ext` is applied live: the window does not',
    'reload, mounted answer inputs are recreated. Load errors are shown in',
    '"Settings → Extensions".',
    '',
    '## Build, check, test',
    '',
    '```sh',
    `pnpm build      # dist-ext/${id}`,
    'pnpm validate   # the same manifest parsing the app does',
    'pnpm lint       # metadata and bundle checks before a catalog pull request',
    'pnpm typecheck  # writes .dolphy/ids.d.ts, then tsc',
    'pnpm test',
    '```',
    '',
    '`.github/workflows/ci.yml` runs the same steps on every push and pull',
    'request.',
    '',
    '## Installation',
    '',
    'From the catalog: Settings → Extensions → Catalog.',
    '',
    `By hand: copy the \`dist-ext/${id}\` directory to`,
    '`<userData>/extensions/` and restart the app.',
    '',
    'To try the extension while developing, set `DOLPHY_DEV_EXTENSIONS` to the',
    'project `dist-ext` directory when starting the app (read only by an',
    'unpackaged app).',
  ]);

export const gitignore = (): string =>
  lines(['node_modules', 'dist-ext', '.dolphy']);

export const claudeMd = (): string => '@AGENTS.md\n';

export const agentsMd = (id: string, module: TemplateModule): string =>
  lines([
    `# ${id}`,
    '',
    'A Dolphy extension project made by `create-dolphy-extension`. Write the',
    'code and the manifest; the build, the checks and the tests are ready.',
    '',
    '## Layout',
    '',
    ...module.layout,
    '- `.github/workflows/ci.yml` — runs the commands below on every push and',
    '  pull request.',
    '',
    '## Commands',
    '',
    '- `pnpm install` — install the toolchain;',
    `- \`pnpm build\` — build into \`dist-ext/${id}\`;`,
    '- `pnpm dev` — rebuild on every change (`dolphy-ext build --watch`);',
    '- `pnpm types` — write `.dolphy/ids.d.ts` from `extension.json`;',
    '- `pnpm typecheck` — `types`, then `tsc`;',
    '- `pnpm validate` — parse the built manifest the way the app does;',
    '- `pnpm lint` — metadata and bundle checks the catalog review also runs;',
    '- `pnpm test` — `vitest`.',
    '',
    'Before a pull request to the catalog run `pnpm build`, `pnpm validate`,',
    '`pnpm lint`, `pnpm typecheck` and `pnpm test`: all must pass.',
    '',
    '## Rules',
    '',
    '- `extension.json` is the only declaration: every id the code registers',
    '  is declared there first. Never edit `.dolphy/ids.d.ts` or `dist-ext/`.',
    `- Keep ids prefixed with the extension id (\`${id}\`).`,
    '- Extension code runs in the extension process (`host`), the app window',
    '  (`views`) or an isolated frame (`panels`, no network). Do not import',
    '  `node:*` modules into code that runs in the window or a frame.',
    '- Before publishing replace `your-github-login` in the `author` field of',
    '  `extension.json` with the GitHub login of the publisher.',
    '- Ask only for the permissions the extension uses, and say in `README.md`',
    '  what each one is for.',
    '- No `eval`, no `new Function`, no minified or obfuscated sources, no',
    '  `http(s)://` URLs unless the manifest declares the `network`',
    '  permission: `pnpm lint` and the catalog review flag them.',
    '- Keep tests next to the behaviour: `@dolphy-app/extension-sdk/testing`',
    '  runs handlers, commands, events, views and panels without the app.',
    '',
    '## Guide',
    '',
    'Start with `node_modules/@dolphy-app/extension-sdk/docs/quick-start.md`;',
    'the recipes next to it show a task type, a theme, a command with a panel,',
    'and events with storage.',
  ]);

export const ciYml = (): string =>
  lines([
    'name: CI',
    '',
    'on:',
    '  push:',
    '  pull_request:',
    '',
    'jobs:',
    '  check:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: pnpm/action-setup@v4',
    '        with:',
    '          version: 10',
    '      - uses: actions/setup-node@v4',
    '        with:',
    '          node-version: 22',
    '      # the project has no lockfile until you commit one',
    '      - run: pnpm install --no-frozen-lockfile',
    '      - run: pnpm build',
    '      - run: pnpm validate',
    '      - run: pnpm lint',
    '      - run: pnpm typecheck',
    '      - run: pnpm test',
  ]);
