/** Extension version in the template and its default for `apiVersion`. */
export const INITIAL_VERSION = '0.1.0';

export const TEMPLATE_NAMES = [
  'exercise',
  'theme',
  'command-panel',
  'react-panel',
  'events',
  'blank',
] as const;
export type TemplateName = (typeof TEMPLATE_NAMES)[number];
export const DEFAULT_TEMPLATE: TemplateName = 'exercise';

export interface TemplateInput {
  id: string;
  /** Project kind; defaults to `exercise`. */
  template?: TemplateName;
  /** Dependency specifiers for the SDK and tools (see `dependencySpecs`). */
  dependencies: { api: string; sdk: string; tools: string };
}

/** What differs between project kinds; the rest of the project is shared. */
export interface TemplateModule {
  /** README paragraph: what the project does. */
  summary: readonly string[];
  /** Bullets of the "Layout" section (README and AGENTS.md). */
  layout: readonly string[];
  /** Project-specific files: relative path → content. */
  files(id: string): Record<string, string>;
  /** Extra `devDependencies` of the project (name → range). */
  devDependencies?: Readonly<Record<string, string>>;
  /** Extra `compilerOptions` of `tsconfig.json` (name → JSON value). */
  compilerOptions?: Readonly<Record<string, string>>;
}

export const lines = (parts: readonly string[]): string =>
  `${parts.join('\n')}\n`;

/** The `pnpm` scripts of every generated project. */
export const scripts = (id: string): Record<string, string> => ({
  build: 'dolphy-ext build',
  dev: 'dolphy-ext build --watch',
  typecheck: 'tsc',
  validate: `dolphy-ext validate dist-ext/${id}`,
  lint: 'dolphy-ext lint',
  test: 'vitest run',
});

export const packageJson = (
  { id, dependencies }: TemplateInput,
  module: TemplateModule,
): string =>
  `${JSON.stringify(
    {
      name: id,
      version: INITIAL_VERSION,
      private: true,
      type: 'module',
      scripts: scripts(id),
      devDependencies: Object.fromEntries(
        Object.entries({
          '@dolphy-app/extension-api': dependencies.api,
          '@dolphy-app/extension-sdk': dependencies.sdk,
          '@dolphy-app/extension-tools': dependencies.tools,
          '@types/node': '^22.20.4',
          'happy-dom': '^20.14.5',
          typescript: '^6.0.3',
          vitest: '^5.0.2',
          vue: '^3.5.35',
          vuetify: '^4.0.1',
          ...module.devDependencies,
        }).sort(([a], [b]) => (a < b ? -1 : 1)),
      ),
    },
    null,
    2,
  )}\n`;

export const tsconfigJson = (module: TemplateModule): string =>
  lines([
    '{',
    '  "compilerOptions": {',
    '    "target": "ES2023",',
    '    "lib": ["ES2023", "DOM"],',
    '    "module": "ESNext",',
    '    "moduleResolution": "bundler",',
    '    "types": ["node"],',
    '    "strict": true,',
    '    "resolveJsonModule": true,',
    '    "allowImportingTsExtensions": true,',
    '    "verbatimModuleSyntax": true,',
    '    "isolatedModules": true,',
    '    "skipLibCheck": true,',
    ...Object.entries(module.compilerOptions ?? {}).map(
      ([name, value]) => `    "${name}": ${value},`,
    ),
    '    "noEmit": true',
    '  },',
    '  "include": ["src", "test"]',
    '}',
  ]);

export const readme = (id: string, module: TemplateModule): string =>
  lines([
    `# ${id}`,
    '',
    ...module.summary,
    'Generated by `create-dolphy-extension`.',
    '',
    '## Layout',
    '',
    ...module.layout,
    '',
    '## Development loop',
    '',
    '```sh',
    'pnpm install',
    `pnpm dev # dolphy-ext build --watch: rebuilds into dist-ext/${id}`,
    '```',
    '',
    'Start the app with the developer root pointing at the `dist-ext` directory',
    'of this project (an absolute path):',
    '',
    '```sh',
    'DOLPHY_DEV_EXTENSIONS=<path to the project>/dist-ext pnpm dev # from the Dolphy repository',
    '```',
    '',
    'A change to a file in `dist-ext` is applied live: the window does not',
    'reload, the components on screen are redrawn. Load errors are shown in',
    '"Settings → Extensions".',
    '',
    '## Build, check, test',
    '',
    '```sh',
    `pnpm build      # dist-ext/${id}`,
    'pnpm validate   # the same manifest parsing the app does',
    'pnpm lint       # metadata and bundle checks before a catalog pull request',
    'pnpm typecheck  # tsc',
    'pnpm test',
    '```',
    '',
    '`.github/workflows/ci.yml` runs the same steps on every push and pull',
    'request.',
    '',
    '## Installation',
    '',
    'From the catalog: Settings → Extensions → Catalog.',
    '',
    `By hand: copy the \`dist-ext/${id}\` directory to`,
    '`<userData>/extensions/` and restart the app.',
    '',
    'To try the extension while developing, set `DOLPHY_DEV_EXTENSIONS` to the',
    'project `dist-ext` directory when starting the app (read only by an',
    'unpackaged app).',
  ]);

export const gitignore = (): string => lines(['node_modules', 'dist-ext']);

export const claudeMd = (): string => '@AGENTS.md\n';

export const agentsMd = (id: string, module: TemplateModule): string =>
  lines([
    `# ${id}`,
    '',
    'A Dolphy extension project made by `create-dolphy-extension`. Write the',
    'code and the manifest; the build, the checks and the tests are ready.',
    '',
    '## Layout',
    '',
    ...module.layout,
    '- `.github/workflows/ci.yml` — runs the commands below on every push and',
    '  pull request.',
    '',
    '## Commands',
    '',
    '- `pnpm install` — install the toolchain;',
    `- \`pnpm build\` — build into \`dist-ext/${id}\`;`,
    '- `pnpm dev` — rebuild on every change (`dolphy-ext build --watch`);',
    '- `pnpm typecheck` — `tsc`;',
    '- `pnpm validate` — parse the built manifest the way the app does;',
    '- `pnpm lint` — metadata and bundle checks the catalog review also runs;',
    '- `pnpm test` — `vitest`.',
    '',
    'Before a pull request to the catalog run `pnpm build`, `pnpm validate`,',
    '`pnpm lint`, `pnpm typecheck` and `pnpm test`: all must pass.',
    '',
    '## Rules',
    '',
    '- `extension.json` holds the identity of the extension only (id, version,',
    '  name, author, tags). Contributions are registered by code: `src/index.ts`',
    '  exports `server` (`defineServer`, runs in the extension host) and/or',
    '  `client` (`defineClient`, runs in the app window). `pnpm build` writes',
    '  `main` and `client` into the built manifest; never edit `dist-ext/`.',
    `- Write ids in the code, prefixed with the extension id (\`${id}\`): a`,
    '  command, an exercise type, a setting, a panel. The host and the window',
    '  refuse an id that is taken or does not carry the prefix.',
    '- The server part (`server`) must not import `vue`, `vuetify` or any',
    '  component. The client part (`client`) is components registered with',
    '  `addPanel`, `addInjection`, `addAnswerView`, `addMarkdownRenderer`: a Vue',
    '  component (`.vue` single-file components and `defineComponent` both work;',
    '  `<v-btn>` and the other Vuetify components in a template need no import)',
    '  or a `Mountable` (`defineMountable` from `@dolphy-app/extension-sdk`):',
    '  an object with `mount(el, ctx)` that draws into `el` with any framework',
    '  and returns the cleanup. The client part must not import `node:*`',
    '  modules. The app gives the client code its own `vue` and `vuetify`:',
    '  import them as usual, they stay out of the bundle. Any other framework',
    '  is a bundled dependency of this extension and is switched on by',
    '  `"frameworks": ["react"]` in `dolphy-ext.config.json` (React is the only',
    '  one so far; `@dolphy-app/extension-sdk/react` has `reactComponent`).',
    '  Keep both parts in separate files that `src/index.ts` re-exports, so the',
    '  build of one never pulls in the other.',
    '- A `<style>` of a single-file component goes into the whole window',
    '  document as a `<style data-dolphy-ext>` tag: write `<style scoped>`.',
    '  `<style module>` and `.vue` files in the server part are not supported.',
    '- Before publishing replace `your-github-login` in the `author` field of',
    '  `extension.json` with the GitHub login of the publisher.',
    '- No `eval`, no `new Function`, no minified or obfuscated sources:',
    '  `pnpm lint` and the catalog review flag them.',
    '- Keep tests next to the behaviour: `createTestServer` from',
    '  `@dolphy-app/extension-sdk/testing` starts `server` on in-memory fakes and',
    '  runs commands, events, schedules, exercise types, importers and',
    '  exporters; `createTestClient` records what `client` adds; mount a Vue',
    '  component with `createApp` from `vue` in `happy-dom`, a `Mountable` with',
    '  `mountForTest`.',
    '',
    '## Guide',
    '',
    'Start with `node_modules/@dolphy-app/extension-sdk/docs/quick-start.md`;',
    'the recipes next to it show a task type, a theme, a command with a panel,',
    'and events with storage.',
  ]);

export const ciYml = (): string =>
  lines([
    'name: CI',
    '',
    'on:',
    '  push:',
    '  pull_request:',
    '',
    'jobs:',
    '  check:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: pnpm/action-setup@v4',
    '        with:',
    '          version: 10',
    '      - uses: actions/setup-node@v4',
    '        with:',
    '          node-version: 22',
    '      # the project has no lockfile until you commit one',
    '      - run: pnpm install --no-frozen-lockfile',
    '      - run: pnpm build',
    '      - run: pnpm validate',
    '      - run: pnpm lint',
    '      - run: pnpm typecheck',
    '      - run: pnpm test',
  ]);
