import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type {
  ExtensionManifest,
  SettingContribution,
} from '@dolphy-app/extension-api';
import type { Project } from './project.ts';

/** Directory of the generated files in a project; never part of `dist-ext` or a catalog source tree. */
export const GENERATED_DIR = '.dolphy';
/** The declarations file, relative to the project root (posix separators, as in `tsconfig` `include`). */
export const IDS_FILE = `${GENERATED_DIR}/ids.d.ts`;

const HEADER =
  '// Generated by `dolphy-ext types` from extension.json. Do not edit: the file is rewritten on every build.';

/** A single-quoted TypeScript string literal. */
const literal = (text: string): string =>
  `'${JSON.stringify(text).slice(1, -1).replaceAll('\\"', '"').replaceAll("'", "\\'")}'`;

/** A union of literals; `never` when the manifest declares none. */
const union = (values: readonly string[]): string =>
  values.length === 0 ? 'never' : values.map(literal).join(' | ');

const settingType = (setting: SettingContribution): string => {
  switch (setting.type) {
    case 'enum':
      return union(setting.options.map((option) => option.value));
    case 'text':
    case 'color':
      return 'string';
    case 'list':
      return 'string[]';
    default:
      return setting.type;
  }
};

const settingsType = (settings: readonly SettingContribution[]): string =>
  settings.length === 0
    ? '{}'
    : `{\n${settings
        .map(
          (setting) => `      ${literal(setting.id)}: ${settingType(setting)};`,
        )
        .join('\n')}\n    }`;

/**
 * The declarations for a manifest: an augmentation of `ExtensionIds` in
 * `@dolphy-app/extension-sdk`. Pure function of the normalized manifest, so
 * the output is deterministic; a kind with no ids is `never`.
 */
export const renderIds = ({ contributes }: ExtensionManifest): string => {
  const entries: [string, string][] = [
    ['exerciseTypes', union(contributes.exerciseTypes.map(({ id }) => id))],
    ['gradePolicies', union(contributes.gradePolicies.map(({ id }) => id))],
    ['commands', union(contributes.commands.map(({ id }) => id))],
    ['events', union(contributes.events.map(({ event }) => event))],
    ['panels', union(contributes.panels.map(({ id }) => id))],
    ['widgets', union(contributes.widgets.map(({ id }) => id))],
    ['importers', union(contributes.importers.map(({ id }) => id))],
    ['exporters', union(contributes.exporters.map(({ id }) => id))],
    [
      'markdownLanguages',
      union(contributes.markdownRenderers.map(({ language }) => language)),
    ],
    ['settings', settingsType(contributes.settings)],
  ];
  return [
    HEADER,
    "declare module '@dolphy-app/extension-sdk' {",
    '  interface ExtensionIds {',
    ...entries.map(([name, type]) => `    ${name}: ${type};`),
    '  }',
    '}',
    '',
    'export {};',
    '',
  ].join('\n');
};

export interface GeneratedIds {
  /** Absolute path of the declarations file. */
  file: string;
  /** `false` when the file already had this content and was left alone. */
  changed: boolean;
}

/**
 * Writes `.dolphy/ids.d.ts` for the project, from `extension.json` only (no
 * author code is run). A file with identical content is not rewritten, so a
 * watcher on the project does not see a change.
 */
export const writeIds = async (project: Project): Promise<GeneratedIds> => {
  const file = path.join(project.root, IDS_FILE);
  const content = renderIds(project.manifest);
  const existing = await readFile(file, 'utf8').catch(() => null);
  if (existing === content) return { file, changed: false };
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, content);
  return { file, changed: true };
};
