//! Copy of the spike adapter `engine-ts/reference/fsrs-scorer/src/lib.rs` (tests dropped):
//! FSRS-6 (fsrs-rs 6.6.2) implementation of Trane's `ExerciseScorer`. Kept verbatim so the
//! L1b golden fixture is generated by the reference code, not by a re-implementation.

//! FSRS-6 backed implementation of Trane's `ExerciseScorer` (spike).
//!
//! The scorer replays the (at most ~20) trials supplied by Trane through `fsrs::FSRS` to get a
//! memory state `(S, D)`, then evaluates retrievability at `now` using fractional days.
//!
//! `ExerciseType` is ignored by FSRS (there is a single decay parameter `w[20]`). In the `Hybrid`
//! variant it is only forwarded to `PowerLawScorer`, which uses it for the performance/velocity
//! part (the weighted average does not depend on the type, but `velocity` and the delta path are
//! evaluated by the same code).

use anyhow::{Result, anyhow};
use fsrs::{DEFAULT_PARAMETERS, FSRS, FSRSItem, FSRSReview, MemoryState, current_retrievability};
use trane::{
    data::{ExerciseDelta, ExerciseScore, ExerciseTrial, ExerciseType},
    exercise_scorer::{ExerciseScorer, PowerLawScorer},
};

/// Default stability (days) at which the `Pure` variant reaches its full value ceiling.
pub const S_PASS: f32 = 2.0;
/// Number of FSRS-6 parameters.
pub const NUM_PARAMS: usize = 21;

const SECONDS_PER_DAY: i64 = 86_400;
/// Gaps above this many days are capped before replay (100 years) to keep the maths finite.
const MAX_DELTA_DAYS: i64 = 36_500;
/// Same clamp range fsrs-rs applies to w[20] (the decay).
const DECAY_MIN: f32 = 0.1;
const DECAY_MAX: f32 = 0.8;

/// How a Trane trial score (1.0..=5.0) is mapped to an FSRS rating (1 Again .. 4 Easy).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RatingMap {
    /// round(score): 1,2 -> Again; 3 -> Hard; 4 -> Good; 5 -> Easy.
    InverseM0,
    /// 1,2 -> Again; 3,4 -> Hard; 5 -> Good.
    RunnerMap,
}

/// How FSRS state is turned into an `ExerciseScore`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Variant {
    /// value = clamp(r * PowerLaw performance score); urgency = 1 - r; velocity from PowerLaw.
    Hybrid,
    /// value = clamp(5 * r * min(1, S / s_pass)); urgency = 1 - r; velocity None.
    Pure,
}

/// FSRS-6 scorer. Immutable after construction, so `Send + Sync`.
#[derive(Clone)]
pub struct FsrsScorer {
    fsrs: FSRS,
    decay: f32,
    pub rating_map: RatingMap,
    pub variant: Variant,
    /// Stability (days) for full value in `Pure`.
    pub s_pass: f32,
}

impl FsrsScorer {
    /// Creates a scorer. `params` must have exactly 21 finite entries.
    pub fn new(params: Vec<f32>, rating_map: RatingMap, variant: Variant) -> Result<Self> {
        if params.len() != NUM_PARAMS {
            return Err(anyhow!("expected {NUM_PARAMS} FSRS-6 parameters, got {}", params.len()));
        }
        if params.iter().any(|p| !p.is_finite()) {
            return Err(anyhow!("FSRS parameters must be finite"));
        }
        let fsrs = FSRS::new(&params).map_err(|e| anyhow!("invalid FSRS parameters: {e:?}"))?;
        Ok(Self {
            fsrs,
            decay: params[20].clamp(DECAY_MIN, DECAY_MAX),
            rating_map,
            variant,
            s_pass: S_PASS,
        })
    }

    /// Scorer with `fsrs::DEFAULT_PARAMETERS`.
    pub fn with_defaults(rating_map: RatingMap, variant: Variant) -> Self {
        Self::new(DEFAULT_PARAMETERS.to_vec(), rating_map, variant).unwrap()
    }

    /// Overrides `S_PASS` (days).
    pub fn with_s_pass(mut self, s_pass: f32) -> Self {
        self.s_pass = s_pass;
        self
    }

    /// Maps a trial score to an FSRS rating; errors on non-finite scores, clamps the rest to 1..5.
    pub fn rating(&self, score: f32) -> Result<u32> {
        if !score.is_finite() {
            return Err(anyhow!("non-finite trial score {score}"));
        }
        let s = score.round().clamp(1.0, 5.0) as u32;
        Ok(match (self.rating_map, s) {
            (_, 1 | 2) => 1,
            (RatingMap::InverseM0, 3) => 2,
            (RatingMap::InverseM0, 4) => 3,
            (RatingMap::InverseM0, _) => 4,
            (RatingMap::RunnerMap, 3 | 4) => 2,
            (RatingMap::RunnerMap, _) => 3,
        })
    }

    /// Replays `trials` (any order; sorted internally if needed) and returns the memory state
    /// after the last review together with that review's timestamp. `None` for empty history.
    pub fn memory_state(&self, trials: &[ExerciseTrial]) -> Result<Option<(MemoryState, i64)>> {
        if trials.is_empty() {
            return Ok(None);
        }
        // Trane passes descending order; iterate in reverse for ascending. Only allocate a sorted
        // copy if the input is not already sorted.
        let sorted;
        let asc: Box<dyn Iterator<Item = &ExerciseTrial>> =
            if trials.windows(2).all(|w| w[0].timestamp >= w[1].timestamp) {
                Box::new(trials.iter().rev())
            } else {
                let mut v: Vec<&ExerciseTrial> = trials.iter().collect();
                v.sort_by_key(|t| t.timestamp);
                sorted = v;
                Box::new(sorted.into_iter())
            };
        let mut reviews = Vec::with_capacity(trials.len());
        let mut prev_ts: Option<i64> = None;
        let mut last_ts = i64::MIN;
        for t in asc {
            let delta_t = match prev_ts {
                None => 0,
                Some(p) => {
                    let gap = (t.timestamp as i128 - p as i128).max(0) / SECONDS_PER_DAY as i128;
                    gap.min(MAX_DELTA_DAYS as i128) as u32
                }
            };
            reviews.push(FSRSReview { rating: self.rating(t.score)?, delta_t });
            prev_ts = Some(t.timestamp);
            last_ts = t.timestamp;
        }
        let state = self
            .fsrs
            .memory_state(FSRSItem { reviews }, None)
            .map_err(|e| anyhow!("FSRS replay failed: {e:?}"))?;
        Ok(Some((state, last_ts)))
    }

    /// Retrievability after `days` fractional days (clamped to >= 0). Always in [0, 1].
    pub fn retrievability(&self, state: MemoryState, days: f32) -> f32 {
        let days = if days.is_nan() { 0.0 } else { days.max(0.0) };
        let r = current_retrievability(state, days, self.decay);
        if r.is_finite() { r.clamp(0.0, 1.0) } else { 0.0 }
    }
}

impl ExerciseScorer for FsrsScorer {
    fn score(
        &self,
        exercise_type: ExerciseType,
        previous_trials: &[ExerciseTrial],
        previous_deltas: &[ExerciseDelta],
        now: i64,
    ) -> Result<ExerciseScore> {
        let Some((state, last_ts)) = self.memory_state(previous_trials)? else {
            return Ok(ExerciseScore { value: 0.0, urgency: 1.0, velocity: None });
        };
        let days = (now as i128 - last_ts as i128).max(0) as f64 / SECONDS_PER_DAY as f64;
        let r = self.retrievability(state, days as f32);
        match self.variant {
            Variant::Pure => {
                let ceiling = if self.s_pass > 0.0 { (state.stability / self.s_pass).min(1.0) } else { 1.0 };
                Ok(ExerciseScore {
                    value: (5.0 * r * ceiling).clamp(0.0, 5.0),
                    urgency: (1.0 - r).clamp(0.0, 1.0),
                    velocity: None,
                })
            }
            Variant::Hybrid => {
                // Time-shift PowerLaw to the newest trial so its own forgetting factor is ~1 and
                // `value` is (weighted performance + delta). PowerLaw needs descending order.
                let mut sorted;
                let trials = if previous_trials.windows(2).all(|w| w[0].timestamp >= w[1].timestamp) {
                    previous_trials
                } else {
                    sorted = previous_trials.to_vec();
                    sorted.sort_by_key(|t| std::cmp::Reverse(t.timestamp));
                    &sorted
                };
                let pl = PowerLawScorer {}.score(exercise_type, trials, previous_deltas, last_ts)?;
                let value = if pl.value.is_finite() { (r * pl.value).clamp(0.0, 5.0) } else { 0.0 };
                Ok(ExerciseScore {
                    value,
                    urgency: (1.0 - r).clamp(0.0, 1.0),
                    velocity: pl.velocity.filter(|v| v.is_finite()),
                })
            }
        }
    }
}
