import { mkdir, readFile, stat, utimes, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { ExtensionManifest } from '@dolphy-app/extension-api';
import { formatDiagnostic, parseManifest } from '@dolphy-app/extension-host';
import { describe, expect, it } from 'vitest';
import { IDS_FILE, renderIds, writeIds } from '../src/ids.ts';
import { loadProject } from '../src/project.ts';
import { makeTemp } from './helpers.ts';

const manifestOf = (
  contributes: Record<string, unknown>,
  extra: Record<string, unknown> = {},
): ExtensionManifest => {
  const parsed = parseManifest({
    id: 'acme.ids',
    version: '1.0.0',
    apiVersion: 1,
    permissions: ['learning.events'],
    ...extra,
    contributes,
  });
  if (!parsed.ok) throw new Error(formatDiagnostic(parsed.diagnostic));
  return parsed.manifest;
};

const schemas = {
  specSchema: { type: 'object' },
  answerSchema: { type: 'string' },
};

/** The lines of one `ExtensionIds` member, e.g. `commands`. */
const member = (text: string, name: string): string => {
  const match = new RegExp(
    `    ${name}: ([\\s\\S]*?);\\n(?:    \\w+: |  \\})`,
  ).exec(text);
  if (match === null) throw new Error(`no '${name}' in\n${text}`);
  return match[1] as string;
};

describe('renderIds', () => {
  it('declares every kind of id the manifest contributes', () => {
    const text = renderIds(
      manifestOf({
        exerciseTypes: [
          { id: 'acme.ids.one', ...schemas },
          { id: 'acme.ids.two', ...schemas },
        ],
        gradePolicies: [{ id: 'acme.ids.strict', label: 'Strict' }],
        commands: [
          { id: 'acme.ids.open', title: 'Open' },
          { id: 'acme.ids.close', title: 'Close', palette: false },
        ],
        events: [{ event: 'attempt.closed' }, { event: 'session.started' }],
        panels: [{ id: 'acme.ids.main', title: 'Main' }],
        markdownRenderers: [{ language: 'echo' }, { language: 'plot-2d' }],
      }),
    );
    expect(text)
      .toBe(`// Generated by \`dolphy-ext types\` from extension.json. Do not edit: the file is rewritten on every build.
declare module '@dolphy-app/extension-sdk' {
  interface ExtensionIds {
    exerciseTypes: 'acme.ids.one' | 'acme.ids.two';
    gradePolicies: 'acme.ids.strict';
    commands: 'acme.ids.open' | 'acme.ids.close';
    events: 'attempt.closed' | 'session.started';
    panels: 'acme.ids.main';
    markdownLanguages: 'echo' | 'plot-2d';
    settings: {};
  }
}

export {};
`);
  });

  it('types a setting by its definition', () => {
    const text = renderIds(
      manifestOf({
        settings: [
          { id: 'acme.ids.on', type: 'boolean', label: 'On', default: true },
          { id: 'acme.ids.name', type: 'string', label: 'Name', default: '' },
          { id: 'acme.ids.goal', type: 'number', label: 'Goal', default: 3 },
          {
            id: 'acme.ids.mode',
            type: 'enum',
            label: 'Mode',
            default: 'fast',
            options: [
              { value: 'fast', label: 'Fast' },
              { value: 'slow', label: 'Slow' },
            ],
          },
        ],
      }),
    );
    expect(member(text, 'settings')).toBe(`{
      'acme.ids.on': boolean;
      'acme.ids.name': string;
      'acme.ids.goal': number;
      'acme.ids.mode': 'fast' | 'slow';
    }`);
  });

  it('keeps quotes and backslashes of an enum option value valid in a literal', () => {
    const value = `it's a \\ "mix"\n`;
    const text = renderIds(
      manifestOf({
        settings: [
          {
            id: 'acme.ids.odd',
            type: 'enum',
            label: 'Odd',
            default: value,
            options: [
              { value, label: 'Odd' },
              { value: 'plain', label: 'Plain' },
            ],
          },
        ],
      }),
    );
    const union = member(text, 'settings').match(
      /'acme\.ids\.odd': (.*);\n/,
    )?.[1];
    // the generated literal evaluates back to the value
    expect(
      new Function(`return [${(union ?? '').replaceAll(' | ', ', ')}]`)(),
    ).toEqual([value, 'plain']);
  });

  it('a manifest without commands, events and panels gives never for them', () => {
    const text = renderIds(
      manifestOf({ exerciseTypes: [{ id: 'acme.ids.one', ...schemas }] }),
    );
    expect(member(text, 'exerciseTypes')).toBe("'acme.ids.one'");
    for (const name of [
      'gradePolicies',
      'commands',
      'events',
      'panels',
      'markdownLanguages',
    ]) {
      expect(member(text, name)).toBe('never');
    }
  });

  it('a manifest with an empty contributes (a theme) declares nothing', () => {
    const text = renderIds(
      manifestOf({
        themes: [
          {
            id: 'acme.ids.theme',
            label: 'Theme',
            dark: true,
            colors: { background: '#000000' },
          },
        ],
      }),
    );
    for (const name of [
      'exerciseTypes',
      'gradePolicies',
      'commands',
      'events',
      'panels',
      'markdownLanguages',
    ]) {
      expect(member(text, name)).toBe('never');
    }
    expect(member(text, 'settings')).toBe('{}');
  });

  it('is a function of the declared ids only', () => {
    const contributes = {
      commands: [{ id: 'acme.ids.open', title: 'Open' }],
    };
    const plain = renderIds(manifestOf(contributes));
    const decorated = renderIds(
      manifestOf(contributes, {
        version: '2.3.4',
        name: 'Ids',
        description: 'Other metadata',
        permissions: [],
      }),
    );
    expect(decorated).toBe(plain);
    expect(renderIds(manifestOf(contributes))).toBe(plain);
  });
});

describe('writeIds', () => {
  const projectWith = async (contributes: object) => {
    const root = await makeTemp();
    await writeFile(
      path.join(root, 'extension.json'),
      JSON.stringify({
        id: 'acme.ids',
        version: '1.0.0',
        apiVersion: 1,
        contributes,
      }),
    );
    return root;
  };

  it('writes .dolphy/ids.d.ts and leaves a file with the same content alone', async () => {
    const root = await projectWith({
      commands: [{ id: 'acme.ids.open', title: 'Open' }],
    });
    const project = await loadProject(root);
    const file = path.join(root, IDS_FILE);

    await expect(writeIds(project)).resolves.toEqual({ file, changed: true });
    expect(await readFile(file, 'utf8')).toBe(renderIds(project.manifest));

    // an old mtime shows whether the second call rewrites the file
    const old = new Date('2020-01-01T00:00:00Z');
    await utimes(file, old, old);
    await expect(writeIds(project)).resolves.toEqual({ file, changed: false });
    expect((await stat(file)).mtime).toEqual(old);
  });

  it('rewrites the file when the declared ids change and replaces a stale one', async () => {
    const root = await projectWith({
      commands: [{ id: 'acme.ids.open', title: 'Open' }],
    });
    await mkdir(path.join(root, '.dolphy'));
    await writeFile(path.join(root, IDS_FILE), '// stale');
    const first = await writeIds(await loadProject(root));
    expect(first.changed).toBe(true);
    expect(await readFile(first.file, 'utf8')).toContain("'acme.ids.open'");

    await writeFile(
      path.join(root, 'extension.json'),
      JSON.stringify({
        id: 'acme.ids',
        version: '1.0.0',
        apiVersion: 1,
        contributes: { commands: [{ id: 'acme.ids.close', title: 'Close' }] },
      }),
    );
    const second = await writeIds(await loadProject(root));
    expect(second.changed).toBe(true);
    const text = await readFile(second.file, 'utf8');
    expect(text).toContain("commands: 'acme.ids.close'");
    expect(text).not.toContain('acme.ids.open');
  });
});
