export const ROUTE = {
  dailyPlan: 'daily-plan',
  courses: 'courses',
  graph: 'graph',
  extensionPanel: 'extension-panel',
  placement: 'placement',
  session: 'session',
  settings: 'settings',
  settingsLearning: 'settings-learning',
  settingsLibrary: 'settings-library',
  settingsAppearance: 'settings-appearance',
  settingsShortcuts: 'settings-shortcuts',
  settingsExtensions: 'settings-extensions',
  settingsExtensionDetails: 'settings-extension-details',
  settingsAbout: 'settings-about',
} as const;
