export { default as SettingsPage } from './ui/SettingsPage.vue';
export { default as SettingsLearning } from './ui/LearningSection.vue';
export { default as SettingsLibrary } from './ui/LibrarySection.vue';
export { default as SettingsAppearance } from './ui/AppearanceSection.vue';
export { default as SettingsShortcuts } from './ui/ShortcutsSection.vue';
export { default as SettingsExtensions } from './ui/ExtensionsSection.vue';
export { default as SettingsExtensionDetails } from './ui/ExtensionDetailsPage.vue';
export { default as SettingsAbout } from './ui/AboutSection.vue';
export { messages as settingsMessages } from './i18n';
export { default as InstallDialog } from './ui/InstallDialog.vue';
export { createInstall, INSTALL_KEY } from './model/install.ts';
export { createInstallLinks } from './model/install-link.ts';
export type { InstallLinkMessage } from './model/install-link.ts';
